import React from 'react';
import { nutritionFor, nutrientGuide } from './nutritionProfiles';
export function NutritionDetails({variety}:{variety:string}) {
  const profile = nutritionFor(variety);
  return <details data-testid="nutrition-details-shop-product-details-details" className="shop-product-details shop-nutrition"><summary data-testid="nutrition-details-nutrition-benefits-summary">Nutrition & benefits</summary>{profile ? <>
    <p data-testid="nutrition-details-nutrition-caption-p" className="nutrition-caption">Nutrients reported in research</p><div data-testid="nutrition-details-nutrition-chips-div" className="nutrition-chips">{profile.nutrients.map(key=><span data-testid={"nutrition-details-span" + "-" + String(key)} key={key}>{nutrientGuide[key].name}</span>)}</div>
    <p data-testid="nutrition-details-p">{profile.note}</p><b data-testid="nutrition-details-nutrition-subtitle-b" className="nutrition-subtitle">What these nutrients do</b><ul data-testid="nutrition-details-ul">{profile.nutrients.map(key=><li data-testid={"nutrition-details-li" + "-" + String(key)} key={key}><strong data-testid={"nutrition-details--strong" + "-" + String(key)}>{nutrientGuide[key].name}: </strong>{nutrientGuide[key].role} <a data-testid={"nutrition-details-nih-a" + "-" + String(key)} href={nutrientGuide[key].source} target="_blank" rel="noopener noreferrer" aria-label={'Read NIH information on '+nutrientGuide[key].name}>NIH ↗</a></li>)}</ul>
    <p data-testid="nutrition-details-nutrition-caveat-p" className="nutrition-caveat">Research highlights, not a tested nutrition label for this harvest. Amounts depend on cultivar, growing conditions, storage, and portion size.</p><a data-testid="nutrition-details-nutrition-source-a" className="nutrition-source" href={profile.source} target="_blank" rel="noopener noreferrer">Microgreen research ↗</a>
  </> : <p data-testid="nutrition-details-a-variety-specific-nutrition-profile-is-not-available-yet-ask-the-farm-for--p">A variety-specific nutrition profile is not available yet. Ask the farm for verified product information.</p>}</details>;
}
export function NutritionGuide() {
  return <section data-testid="nutrition-guide-nutrition-section" className="shop-nutrition-guide" id="nutrition"><div data-testid="nutrition-guide-div"><p data-testid="nutrition-guide-shop-eyebrow-p" className="shop-eyebrow">SMALL LEAVES, MORE TO DISCOVER</p><h2 data-testid="nutrition-guide-get-to-know-your-greens-h2">Get to know your greens.</h2><p data-testid="nutrition-guide-microgreens-can-add-variety-to-a-balanced-diet-explore-the-nutrient-roles-b-p">Microgreens can add variety to a balanced diet. Explore the nutrient roles below and open each product’s nutrition section for variety-specific research.</p></div><div data-testid="nutrition-guide-nutrition-guide-grid-div" className="nutrition-guide-grid">{Object.entries(nutrientGuide).map(([key,value])=><a data-testid={"nutrition-guide-a" + "-" + String(key)} key={key} href={value.source} target="_blank" rel="noopener noreferrer"><span data-testid={"nutrition-guide-nutrition-letter-span" + "-" + String(key)} className="nutrition-letter">{key}</span><h3 data-testid={"nutrition-guide-h3" + "-" + String(key)}>{value.name}</h3><p data-testid={"nutrition-guide-p" + "-" + String(key)}>{value.role}</p><small data-testid={"nutrition-guide-learn-more-at-nih-small" + "-" + String(key)}>Learn more at NIH ↗</small></a>)}</div><p data-testid="nutrition-guide-nutrition-guide-note-p" className="nutrition-guide-note">We don’t publish calories, nutrient amounts, or daily-value percentages without harvest-specific analysis. These notes explain nutrient functions, not guaranteed health outcomes from a serving.</p></section>;
}
