import React, { useEffect, useState } from 'react';
import { api, money } from './api';
export default function StoreSettings() {
  const [values, setValues] = useState({ upiId: '', upiPayeeName: '', razorpayPaymentPage: '' });
  const [rows, setRows] = useState<any[]>([]), [links, setLinks] = useState<Record<string,string>>({});
  const [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const load = () => api('store-checkouts').then(setRows).catch(e => setError(e.message));
  useEffect(() => { api('settings').then(s => setValues({ upiId: s.upiId || '', upiPayeeName: s.upiPayeeName || '', razorpayPaymentPage: s.razorpayPaymentPage || '' })).catch(e => setError(e.message)); load(); }, []);
  return <section data-testid="store-settings-panel-section" className="panel settings-form" style={{ gridColumn: '1 / -1' }}><h2 data-testid="store-settings-customer-store-payments-h2">Customer store & payments</h2><p data-testid="store-settings-p"><a data-testid="store-settings-open-the-customer-store-a" href="/shop" target="_blank" rel="noopener noreferrer">Open the customer store ↗</a></p>
    <form data-testid="store-settings-form" onSubmit={async e => { e.preventDefault(); setError(''); setMessage(''); setBusy(true); try { const current = await api('settings'); await api('settings', { method:'PATCH', body:JSON.stringify({ businessName:current.businessName || 'Kovai Greens', farmAddress:current.farmAddress || '', ...values }) }); setMessage('Customer payment details saved.'); } catch(e:any){ setError(e.message); } finally { setBusy(false); } }}>
      <label data-testid="store-settings-upi-id-label">UPI ID<input data-testid="store-settings-your-business-bank-input" value={values.upiId} onChange={e=>setValues({...values,upiId:e.target.value})} placeholder="your-business@bank"/></label>
      <label data-testid="store-settings-upi-payee-name-label">UPI payee name<input data-testid="store-settings-name-customers-should-verify-input" value={values.upiPayeeName} onChange={e=>setValues({...values,upiPayeeName:e.target.value})} placeholder="Name customers should verify"/></label>
      <label data-testid="store-settings-razorpay-me-profile-or-reusable-payment-page-optional-label">Razorpay.me profile or reusable Payment Page (optional)<input data-testid="store-settings-https-pages-razorpay-com-input" type="url" value={values.razorpayPaymentPage} onChange={e=>setValues({...values,razorpayPaymentPage:e.target.value})} placeholder="https://pages.razorpay.com/..."/></label>
      <p data-testid="store-settings-upi-qr-codes-include-the-order-amount-and-reference-use-a-razorpay-me-profi-p">UPI QR codes include the order amount and reference. Use a Razorpay.me profile or reusable Payment Page here; assign single-use Razorpay Payment Links to individual orders below. No gateway keys are required.</p>
      <button data-testid="store-settings-button-button" className="button primary" disabled={busy}>Save payment details</button>
    </form>{error&&<p data-testid="store-settings-error-p" className="error" role="alert">{error}</p>}{message&&<p data-testid="store-settings-p-2" role="status">{message}</p>}
    <h2 data-testid="store-settings-customer-web-orders-h2" style={{marginTop:32}}>Customer web orders</h2><p data-testid="store-settings-payment-references-are-unverified-check-your-bank-or-razorpay-then-record-t-p">Payment references are unverified. Check your bank or Razorpay, then record the actual receipt under Payments. A customer submission never marks an order paid.</p>
    <button data-testid="store-settings-button-button-2" className="button secondary" onClick={load}>Refresh orders</button>
    {!rows.length?<p data-testid="store-settings-no-customer-web-orders-yet-p">No customer web orders yet.</p>:<div data-testid="store-settings-div" style={{overflowX:'auto',marginTop:16}}><table data-testid="store-settings-table" style={{width:'100%',fontSize:13,borderCollapse:'collapse'}}><thead data-testid="store-settings-thead"><tr data-testid="store-settings-tr"><th data-testid="store-settings-order-customer-th">Order / Customer</th><th data-testid="store-settings-total-reference-th">Total / Reference</th><th data-testid="store-settings-razorpay-payment-link-th">Razorpay Payment Link</th></tr></thead><tbody data-testid="store-settings-tbody">{rows.map(r=><tr data-testid={"store-settings-tr-2" + "-" + String(r.id)} key={r.id}><td data-testid={"store-settings-td" + "-" + String(r.id)} style={{padding:12,verticalAlign:'top'}}><b data-testid={"store-settings-b" + "-" + String(r.id)}>{r.order.number}</b><p data-testid={"store-settings-p-3" + "-" + String(r.id)}>{r.order.customer.name}</p><small data-testid={"store-settings-small" + "-" + String(r.id)}>{r.order.status}</small><p data-testid={"store-settings-p-4" + "-" + String(r.id)}><a data-testid={"store-settings-customer-order-page-a" + "-" + String(r.id)} href={'/shop/order/'+r.token} target="_blank" rel="noopener noreferrer">Customer order page ↗</a></p></td><td data-testid={"store-settings-td-2" + "-" + String(r.id)} style={{padding:12,verticalAlign:'top'}}>{money(r.order.totalPaise)}<p data-testid={"store-settings-p-5" + "-" + String(r.id)}>{r.paymentReference||'No reference submitted'}</p><a data-testid={"store-settings-record-verified-payment-a" + "-" + String(r.id)} href="/payments">Record verified payment →</a></td><td data-testid={"store-settings-td-3" + "-" + String(r.id)} style={{padding:12,minWidth:250}}><form data-testid={"store-settings-form-2" + "-" + String(r.id)} onSubmit={async e=>{e.preventDefault();setError('');try{await api('store-checkouts/'+r.id+'/payment-link',{method:'PATCH',body:JSON.stringify({url:links[r.id]??r.razorpayLink})});setMessage('Order payment link saved.');load();}catch(e:any){setError(e.message);}}}><input data-testid={"store-settings-https-rzp-io-input" + "-" + String(r.id)} type="url" aria-label={'Razorpay link for '+r.order.number} placeholder="https://rzp.io/..." value={links[r.id]??r.razorpayLink} onChange={e=>setLinks({...links,[r.id]:e.target.value})}/><button data-testid={"store-settings-button-button-3" + "-" + String(r.id)} className="button secondary">Save order link</button></form></td></tr>)}</tbody></table></div>}
  </section>;
}
